# Generated by Django 4.1.3 on 2023-12-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product_handover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='主键ID')),
                ('create_user', models.IntegerField(default=0, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, max_length=11, null=True, verbose_name='创建时间')),
                ('update_user', models.IntegerField(default=0, verbose_name='更新人')),
                ('update_time', models.DateTimeField(auto_now=True, max_length=11, null=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=0, verbose_name='逻辑删除')),
                ('time', models.DateTimeField(help_text='日期', max_length=18, verbose_name='日期')),
                ('work_order', models.CharField(help_text='工单号', max_length=255, verbose_name='工单号')),
                ('name', models.CharField(help_text='客户名称', max_length=255, verbose_name='客户名称')),
                ('code', models.CharField(help_text='规格型号', max_length=255, verbose_name='规格型号')),
                ('remark', models.CharField(help_text='安数', max_length=255, null=True, verbose_name='安数')),
                ('delivery_time', models.DateTimeField(help_text='交货日期', max_length=18, null=True, verbose_name='交货日期')),
                ('quantity', models.IntegerField(help_text='数量', null=True, verbose_name='数量')),
                ('control_version', models.CharField(help_text='主控板版本号', max_length=255, null=True, verbose_name='主控板版本号')),
                ('execute_version', models.CharField(help_text='执行版版本号', max_length=255, verbose_name='执行版版本号')),
            ],
            options={
                'verbose_name': '产品交接表',
                'verbose_name_plural': '产品交接表',
                'db_table': 'django_product_handover',
            },
        ),
    ]
