# Generated by Django 4.1.3 on 2024-01-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Followup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='主键ID')),
                ('create_user', models.IntegerField(default=0, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, max_length=11, null=True, verbose_name='创建时间')),
                ('update_user', models.IntegerField(default=0, verbose_name='更新人')),
                ('update_time', models.DateTimeField(auto_now=True, max_length=11, null=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=0, verbose_name='逻辑删除')),
                ('work_order', models.CharField(help_text='工单号', max_length=255, verbose_name='工单号')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('product_name', models.CharField(help_text='产品名称', max_length=255, verbose_name='产品名称')),
                ('commit_user', models.CharField(help_text='填写者', max_length=255, verbose_name='填写者')),
                ('item_number', models.CharField(help_text='产品型号', max_length=255, verbose_name='产品型号')),
                ('qty_obj_hour', models.IntegerField(help_text='ERP目标', verbose_name='ERP目标')),
                ('qty_prod_hour', models.IntegerField(help_text='实际产出', verbose_name='实际产出')),
                ('cumul_qty_obj', models.IntegerField(help_text='ERP目标累计', verbose_name='ERP目标累计')),
                ('cumul_qty_prod', models.IntegerField(help_text='实际累计', verbose_name='实际累计')),
                ('loss_time', models.IntegerField(help_text='损耗工时', verbose_name='损耗工时')),
                ('changeover_time', models.IntegerField(help_text='换线时间', verbose_name='换线时间')),
                ('signal', models.IntegerField(choices=[(1, '红色'), (2, '绿色')], default=1, help_text='信号：1-红色 2-绿色', verbose_name='信号：1-红色 2-绿色')),
                ('product_module', models.IntegerField(choices=[(1, '成品'), (2, '模块')], default=1, help_text='成品/模块：1-成品 2-模块', verbose_name='成品/模块：1-成品 2-模块')),
                ('problem', models.TextField(help_text='问题', null=True, verbose_name='问题')),
                ('action', models.TextField(help_text='行动', null=True, verbose_name='行动')),
                ('remark', models.TextField(help_text='备注', null=True, verbose_name='备注')),
                ('work_hours', models.IntegerField(help_text='工时', verbose_name='工时')),
            ],
            options={
                'verbose_name': '组装跟进表',
                'verbose_name_plural': '组装跟进表',
                'db_table': 'django_followup',
            },
        ),
    ]
