# Generated by Django 4.1.3 on 2024-01-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='主键ID')),
                ('create_user', models.IntegerField(default=0, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, max_length=11, null=True, verbose_name='创建时间')),
                ('update_user', models.IntegerField(default=0, verbose_name='更新人')),
                ('update_time', models.DateTimeField(auto_now=True, max_length=11, null=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=0, verbose_name='逻辑删除')),
                ('softwareType', models.CharField(help_text='软件类型', max_length=150, verbose_name='软件类型')),
                ('productType', models.CharField(help_text='产品类型', max_length=150, verbose_name='产品类型')),
                ('productSN', models.CharField(help_text='产品SN', max_length=150, verbose_name='产品SN')),
                ('macAddress', models.CharField(help_text='mac地址', max_length=150, verbose_name='mac地址')),
                ('result', models.IntegerField(choices=[(1, '通过'), (2, '失败')], default=1, help_text='结果：1-通过 2-失败', verbose_name='结果：1-通过 2-失败')),
                ('softwareVersion', models.CharField(help_text='软件版本', max_length=30, verbose_name='软件版本')),
                ('companyName', models.CharField(help_text='公司名', max_length=150, verbose_name='公司名')),
                ('protocolVersion', models.CharField(help_text='协议版本', max_length=30, verbose_name='协议版本')),
                ('testStartTime', models.DateTimeField(max_length=11, verbose_name='测试开始时间')),
                ('testEndTime', models.DateTimeField(max_length=11, verbose_name='测试结束时间')),
                ('testTime', models.CharField(help_text='测试时间', max_length=150, verbose_name='测试时间')),
                ('work_order', models.CharField(help_text='工单号', max_length=255, verbose_name='工单号')),
                ('goods_SN', models.CharField(help_text='成品SN', max_length=255, verbose_name='成品SN')),
            ],
            options={
                'verbose_name': '测试数据',
                'verbose_name_plural': '测试数据',
                'db_table': 'django_testdata',
            },
        ),
    ]
