# Generated by Django 4.1.3 on 2024-01-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='主键ID')),
                ('product_id', models.IntegerField(default=0, help_text='成品序列Id', verbose_name='成品序列Id')),
                ('module_SN', models.CharField(help_text='模块码', max_length=255, verbose_name='模块码')),
            ],
            options={
                'verbose_name': '模块',
                'verbose_name_plural': '模块',
                'db_table': 'django_bind_module',
            },
        ),
    ]
