# Generated by Django 4.1.3 on 2023-12-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Softwarerelease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='主键ID')),
                ('create_user', models.IntegerField(default=0, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, max_length=11, null=True, verbose_name='创建时间')),
                ('update_user', models.IntegerField(default=0, verbose_name='更新人')),
                ('update_time', models.DateTimeField(auto_now=True, max_length=11, null=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=0, verbose_name='逻辑删除')),
                ('name', models.CharField(help_text='程序名称', max_length=255, null=True, verbose_name='程序名称')),
                ('products', models.CharField(help_text='使用产品', max_length=255, null=True, verbose_name='使用产品')),
                ('history_version', models.CharField(help_text='历史版本', max_length=255, null=True, verbose_name='历史版本')),
                ('version', models.CharField(help_text='当前版本', max_length=255, null=True, verbose_name='当前版本')),
                ('modify_time', models.DateTimeField(help_text='修改日期', max_length=18, null=True, verbose_name='修改日期')),
                ('version_explain', models.CharField(help_text='版本说明', max_length=255, null=True, verbose_name='版本说明')),
                ('updata', models.CharField(help_text='此次更新', max_length=255, null=True, verbose_name='此次更新')),
                ('burn_method', models.CharField(help_text='烧录方法', max_length=255, null=True, verbose_name='烧录方法')),
                ('upgrade_method', models.CharField(help_text='升级方法', max_length=150, null=True, verbose_name='升级方法')),
                ('calibration_method', models.CharField(help_text='校准方法', max_length=150, null=True, verbose_name='校准方法')),
                ('User_Manual', models.CharField(help_text='用户手册', max_length=150, null=True, verbose_name='用户手册')),
                ('upgrade_cause', models.CharField(help_text='升级原因', max_length=255, null=True, verbose_name='升级原因')),
                ('documentation_position', models.CharField(help_text='程序和文档公盘位置', max_length=255, null=True, verbose_name='程序和文档公盘位置')),
                ('User_Manual_position', models.CharField(help_text='用户使用手册和协议公盘位置', max_length=255, null=True, verbose_name='用户使用手册和协议公盘位置')),
                ('attachment', models.CharField(help_text='附件', max_length=1000, null=True, verbose_name='附件')),
            ],
            options={
                'verbose_name': '出厂报告表',
                'verbose_name_plural': '出厂报告表',
                'db_table': 'django_softwarerelease',
            },
        ),
    ]
