# Generated by Django 4.1.3 on 2024-01-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='主键ID')),
                ('create_user', models.IntegerField(default=0, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, max_length=11, null=True, verbose_name='创建时间')),
                ('update_user', models.IntegerField(default=0, verbose_name='更新人')),
                ('update_time', models.DateTimeField(auto_now=True, max_length=11, null=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=0, verbose_name='逻辑删除')),
                ('work_order', models.CharField(help_text='工单号', max_length=255, verbose_name='工单号')),
                ('product_name', models.CharField(help_text='产品名称', max_length=255, verbose_name='产品名称')),
                ('respon', models.CharField(help_text='责任归属人', max_length=255, verbose_name='责任归属人')),
                ('item_number', models.CharField(help_text='产品型号', max_length=255, verbose_name='产品型号')),
                ('rw_qty', models.IntegerField(help_text='返工数量', verbose_name='返工数量')),
                ('loss_time', models.IntegerField(help_text='损耗工时', verbose_name='损耗工时')),
                ('loss_material_qty', models.IntegerField(help_text='损耗材料数量', verbose_name='损耗材料数量')),
                ('loss_material_name', models.CharField(help_text='损耗材料名称', max_length=255, verbose_name='损耗材料名称')),
                ('rw_reason', models.IntegerField(choices=[(1, '物料不良/半成品/成品返工工时'), (2, '返工/正常作业/原料报废'), (3, '客户退回产品的维修')], default=1, help_text='返工原因：1-物料不良/半成品/成品返工工时 2-返工/正常作业/原料报废 3-客户退回产品的维修', verbose_name='返工原因：1-物料不良/半成品/成品返工工时 2-返工/正常作业/原料报废 3-客户退回产品的维修')),
                ('product_module', models.IntegerField(choices=[(1, '成品'), (2, '模块')], default=1, help_text='成品/模块：1-成品 2-模块', verbose_name='成品/模块：1-成品 2-模块')),
            ],
            options={
                'verbose_name': '返工记录表',
                'verbose_name_plural': '返工记录表',
                'db_table': 'django_rework',
            },
        ),
    ]
