# Generated by Django 4.1.3 on 2024-01-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Debug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='主键ID')),
                ('create_user', models.IntegerField(default=0, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, max_length=11, null=True, verbose_name='创建时间')),
                ('update_user', models.IntegerField(default=0, verbose_name='更新人')),
                ('update_time', models.DateTimeField(auto_now=True, max_length=11, null=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=0, verbose_name='逻辑删除')),
                ('work_order', models.CharField(help_text='工单号', max_length=255, verbose_name='工单号')),
                ('order_time', models.DateTimeField(max_length=11, verbose_name='下单日期')),
                ('client_name', models.CharField(help_text='客户名称', max_length=255, verbose_name='客户名称')),
                ('shape', models.CharField(help_text='规格型号', max_length=255, verbose_name='规格型号')),
                ('product_name', models.CharField(help_text='产品名称', max_length=255, verbose_name='产品名称')),
                ('product_count', models.IntegerField(default=0, help_text='数量', verbose_name='数量')),
                ('submit_time', models.DateTimeField(max_length=11, verbose_name='交期')),
                ('instruction', models.CharField(help_text='具体说明', max_length=255, null=True, verbose_name='具体说明')),
                ('remark', models.CharField(help_text='备注', max_length=255, null=True, verbose_name='备注')),
                ('product_module', models.IntegerField(choices=[(1, '成品'), (2, '模块')], help_text='成品_模块：1-成品 2-模块', verbose_name='成品_模块：1-成品 2-模块')),
                ('start_time', models.DateTimeField(max_length=11, verbose_name='开始日期')),
                ('finish_time', models.DateTimeField(max_length=11, verbose_name='开始日期')),
                ('work_hours', models.DecimalField(decimal_places=6, help_text='所用工时', max_digits=10, null=True, verbose_name='所用工时')),
                ('debug_count', models.IntegerField(default=0, help_text='调试数量', verbose_name='调试数量')),
            ],
            options={
                'verbose_name': '调试报表',
                'verbose_name_plural': '调试报表',
                'db_table': 'django_debugreport',
            },
        ),
    ]
