# Generated by Django 4.1.3 on 2023-12-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='主键ID')),
                ('create_user', models.IntegerField(default=0, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, max_length=11, null=True, verbose_name='创建时间')),
                ('update_user', models.IntegerField(default=0, verbose_name='更新人')),
                ('update_time', models.DateTimeField(auto_now=True, max_length=11, null=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=0, verbose_name='逻辑删除')),
                ('content', models.TextField(help_text='需求或建议', null=True, verbose_name='需求或建议')),
                ('commit_user', models.CharField(help_text='提交者', max_length=40, null=True, verbose_name='提交者')),
                ('status', models.IntegerField(choices=[(1, '未查看'), (2, '确认'), (3, '完成'), (4, '不通过')], default=1, help_text='处理状态：1-未查看 2-确认 3-完成 4-未通过', verbose_name='处理状态：1-未查看 2-确认 3-完成 4-未通过')),
                ('type', models.IntegerField(choices=[(1, '问题'), (2, '建议'), (3, '新需求')], default=1, help_text='类型：1-问题 2-建议 3-新需求 ', verbose_name='类型：1-问题 2-建议 3-新需求 ')),
                ('feedback', models.TextField(help_text='反馈内容', verbose_name='反馈内容')),
                ('priority', models.IntegerField(default=10, help_text='优先级', verbose_name='优先级')),
            ],
            options={
                'verbose_name': '意见反馈',
                'verbose_name_plural': '意见反馈',
                'db_table': 'django_suggestion',
            },
        ),
    ]
