# Generated by Django 4.1.3 on 2023-11-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestDataTestStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='主键ID')),
                ('testdata_id', models.IntegerField(default=0, help_text='测试数据表ID', verbose_name='测试数据表ID')),
                ('no', models.CharField(help_text='测试步骤编号', max_length=30, verbose_name='测试步骤编号')),
                ('name', models.CharField(help_text='测试步骤名称', max_length=150, verbose_name='测试步骤名称')),
                ('result', models.IntegerField(choices=[(1, '通过'), (2, '失败')], default=1, help_text='结果：1-通过 2-失败', verbose_name='结果：1-通过 2-失败')),
            ],
            options={
                'verbose_name': '测试数据_测试步骤',
                'verbose_name_plural': '测试数据_测试步骤',
                'db_table': 'django_testdata_teststep',
            },
        ),
    ]
